[workspace]
resolver = "3"
members = [
    "crates/anvil",
    "crates/cli",
    "crates/core",
    "crates/evmsketch",
    "crates/gas-estimator",
    "crates/rpc",
    "crates/wasm",
    "crates/indexer-api",
    "crates/indexer-rpc",
    "crates/indexer-store",
    "crates/indexer-resolver",
    "crates/indexer-service",
    "crates/indexer-web",
]
default-members = [
    "crates/core",
    "crates/gas-estimator",
    "crates/rpc",
    "crates/evmsketch",
    "crates/cli",
]

[profile.bench]
debug = 1
