//! UNBOUNDED_V3 M3 — the ffi ≡ precompile differential.
//!
//! The ffi leg lives in gas-killer/solidity-sdk: `test/GkVmParity.t.sol` runs
//! every golden `gk-run` vector as a TASK — a call to `GkVmParityConsumer`
//! wired to `GkVmFfiShim` — and records what the task did to the consumer as
//! the encoded `StateUpdate` payload (`tests/fixtures/gkvm/parity_tasks.json`,
//! regenerated by `make -C tools/gk parity`, together with the consumer's
//! production runtime bytecode, `GKVM = GKVM_ADDRESS`).
//!
//! The precompile leg is here: the same bytecode, the same calldata, through
//! the local executor's real extraction against the real precompile. The
//! payload bytes must be identical — including the typed failure bytes
//! `probe` folds into its log, and including `GkGuestOutOfCycles`'s budget
//! word, which the pinned tasks reproduce by forwarding exactly the gas that
//! makes the precompile's own budget the vectors' pinned 1000 cycles.
//!
//! Also here, per the milestone: the classify pass needs no fallback for a
//! gkvm task, a forced replay pass is answered from the result memo, both
//! legs sit under one env commitment, and the negative that documents the
//! `requiresGuestVm` gate — the `rpc` executor deterministically turns a V3
//! task into the `GkVmUnavailable` revert transition.

use super::*;
use crate::local_exec::{
    ExecMounts, call_view_local_blocking, extract_state_updates_local,
    extract_state_updates_local_blocking,
};
use alloy::primitives::keccak256;
use gas_analyzer_core::gkvm::errors::{self, SolError};
use gas_analyzer_core::gkvm::{
    GKVM_ADDRESS, GkvmEnv, UNBOUNDED_V3_CYCLES_PER_GAS, UNBOUNDED_V3_GKVM_SPEC_VERSION,
    cycles_to_gas, env_commitment_v3,
};
use gas_analyzer_core::validate_unbounded_shape;
use gas_analyzer_gkvm::{GuestProgramSet, LoadedGuestProgram};
use revm::database::{CacheDB, EmptyDB};
use revm::state::{AccountInfo, Bytecode};

const HELLO_C: &[u8] = include_bytes!("../../../gkvm/tests/fixtures/hello-c.elf");
const BENCH_C: &[u8] = include_bytes!("../../../gkvm/tests/fixtures/bench-c.elf");

const PARITY_TASKS: &str = include_str!("../../tests/fixtures/gkvm/parity_tasks.json");
const GOLDEN_VECTORS: [&str; 3] = [
    include_str!("../../tests/fixtures/gkvm/hello-c_vectors.json"),
    include_str!("../../tests/fixtures/gkvm/bench-c_vectors.json"),
    include_str!("../../tests/fixtures/gkvm/bench-c-limit1000_vectors.json"),
];

const CALLER: Address = address!("0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266");
const CONSUMER: Address = address!("0x00000000000000000000000000000000000050a1");

#[derive(serde::Deserialize)]
#[serde(rename_all = "camelCase")]
struct ParityFixture {
    gkvm_address: Address,
    consumer_code: Bytes,
    tasks: Vec<ParityTask>,
}

/// One ffi-leg task: `calldata` sent to a fresh consumer, and the encoded
/// payload forge observed (`revert_data` when the tracked call reverted).
#[derive(serde::Deserialize)]
#[serde(rename_all = "camelCase")]
struct ParityTask {
    vector: String,
    #[serde(rename = "fn")]
    function: String,
    calldata: Bytes,
    success: bool,
    revert_data: Bytes,
    storage_updates: Bytes,
}

impl ParityTask {
    fn id(&self) -> String {
        format!("{} via {}", self.vector, self.function)
    }
}

#[derive(serde::Deserialize)]
#[serde(rename_all = "camelCase")]
struct GoldenVectors {
    program_hash: B256,
    vectors: Vec<GoldenVector>,
}

#[derive(serde::Deserialize)]
#[serde(rename_all = "camelCase")]
struct GoldenVector {
    cycles: u64,
    gas_used: u64,
}

fn fixture() -> ParityFixture {
    let fixture: ParityFixture = serde_json::from_str(PARITY_TASKS).expect("parity_tasks.json");
    assert_eq!(
        fixture.gkvm_address, GKVM_ADDRESS,
        "ffi leg built for another precompile address"
    );
    fixture
}

/// The first recorded task for `vector` through `function`.
fn task<'a>(fixture: &'a ParityFixture, vector: &str, function: &str) -> &'a ParityTask {
    fixture
        .tasks
        .iter()
        .find(|task| task.vector == vector && task.function == function)
        .unwrap_or_else(|| panic!("no parity task {vector} via {function}"))
}

fn host() -> Arc<GkvmHost> {
    let mut programs = GuestProgramSet::default();
    for elf in [HELLO_C, BENCH_C] {
        programs.insert_program(
            LoadedGuestProgram::from_bytes(elf.to_vec(), keccak256(elf), "<fixture>")
                .expect("fixture loads"),
        );
    }
    Arc::new(GkvmHost::new(programs))
}

fn mounts(host: &Arc<GkvmHost>) -> ExecMounts {
    ExecMounts {
        overlay: Default::default(),
        gkvm: Some(host.clone()),
    }
}

/// A fresh consumer, as on the ffi leg: production bytecode, all-zero storage.
fn consumer_db(fixture: &ParityFixture) -> CacheDB<EmptyDB> {
    let mut db = CacheDB::new(EmptyDB::default());
    db.insert_account_info(
        CONSUMER,
        AccountInfo::from_bytecode(Bytecode::new_raw(fixture.consumer_code.clone())),
    );
    db
}

fn block_env() -> LocalBlockEnv {
    LocalBlockEnv {
        chain_id: 31_337,
        spec: SpecId::PRAGUE,
        number: 100,
        timestamp: 1_700_000_000,
        gas_limit: 30_000_000,
        coinbase: Address::ZERO,
        prevrandao: B256::ZERO,
        basefee: 0,
        difficulty: U256::ZERO,
    }
}

fn task_request(calldata: &Bytes) -> TransactionRequest {
    TransactionRequest::default()
        .from(CALLER)
        .to(CONSUMER)
        .gas_limit(30_000_000)
        .input(calldata.clone().into())
}

fn local_tx(calldata: &Bytes) -> LocalTxRequest {
    LocalTxRequest::from_request(&task_request(calldata)).expect("valid tx request")
}

/// The precompile leg of one task: the local executor's real extraction.
fn extract(
    fixture: &ParityFixture,
    host: &Arc<GkvmHost>,
    calldata: &Bytes,
    profile: SimProfile,
) -> Vec<StateUpdate> {
    extract_state_updates_local_blocking(
        consumer_db(fixture),
        mounts(host),
        &block_env(),
        &local_tx(calldata),
        profile,
        CONSUMER,
    )
    .expect("local extraction")
    .0
}

#[test]
fn ffi_and_precompile_tasks_encode_identical_state_updates() {
    let fixture = fixture();
    assert_eq!(fixture.tasks.len(), 17);

    // Chain is the forge-like env; UnboundedV1 is the profile V3 consumers
    // run under (2^40 gas, single-slot payload shape enforced).
    for profile in [SimProfile::Chain, SimProfile::UnboundedV1] {
        for task in &fixture.tasks {
            let host = host();
            let updates = extract(&fixture, &host, &task.calldata, profile);
            assert_eq!(
                encode_state_updates_to_abi(&updates),
                task.storage_updates,
                "{} under {profile:?}: precompile-leg payload diverged from the ffi leg\n  \
                 precompile: {updates:?}",
                task.id()
            );

            if task.success {
                let shape = validate_unbounded_shape(&updates).expect("unbounded payload shape");
                assert_eq!((shape.stores, shape.calls, shape.logs), (1, 0, 1));
            } else {
                // A bubbled guest failure is the revert transition: nothing to
                // apply, and the revert reason is the ffi leg's, byte for byte.
                assert!(updates.is_empty());
                let err = call_view_local_blocking(
                    consumer_db(&fixture),
                    mounts(&host),
                    &block_env(),
                    &local_tx(&task.calldata),
                    profile,
                )
                .expect_err("the tracked call reverts");
                assert!(
                    format!("{err:#}").contains(&task.revert_data.to_string()),
                    "{}: revert data diverged: {err:#}",
                    task.id()
                );
            }
        }
    }
}

#[test]
fn the_classify_pass_needs_no_fallback_for_a_gkvm_task() {
    // Every pass of an extraction reaches the precompile, so the host's
    // counters say how many passes ran: a fallback would be a second pass,
    // visible as a memo hit.
    let fixture = fixture();
    for function in ["ask", "probe"] {
        for vector in ["hello-c_vectors.json#1", "bench-c_vectors.json#1"] {
            let host = host();
            let task = task(&fixture, vector, function);
            assert!(task.success);
            extract(&fixture, &host, &task.calldata, SimProfile::UnboundedV1);
            assert_eq!(
                (host.guest_runs(), host.memo_hits()),
                (1, 0),
                "{}: exactly one pass, the classify pass, reached the guest",
                task.id()
            );
        }
    }

    // A caught guest failure keeps the fast path too: `probe`'s reverted
    // frame is a STATICCALL, which classification ignores.
    let host = host();
    let trapped = task(&fixture, "bench-c_vectors.json#2", "probe");
    extract(&fixture, &host, &trapped.calldata, SimProfile::UnboundedV1);
    assert_eq!((host.guest_runs(), host.memo_hits()), (1, 0));
}

#[test]
fn a_second_pass_is_answered_from_the_memo() {
    let fixture = fixture();

    // The same task again (view serving, a retried round): one guest run.
    let host = host();
    let answered = task(&fixture, "bench-c_vectors.json#1", "ask");
    let first = extract(&fixture, &host, &answered.calldata, SimProfile::UnboundedV1);
    let second = extract(&fixture, &host, &answered.calldata, SimProfile::UnboundedV1);
    assert_eq!(
        encode_state_updates_to_abi(&first),
        encode_state_updates_to_abi(&second)
    );
    assert_eq!(
        encode_state_updates_to_abi(&second),
        answered.storage_updates
    );
    assert_eq!((host.guest_runs(), host.memo_hits()), (1, 1));

    // The real classify → replay fallback: a bubbled trap reverts the tracked
    // call, classification falls back, and the replay-script pass re-executes
    // the transaction — its guest call is the memo's, not a second run.
    let replayed = self::host();
    let trapped = task(&fixture, "bench-c_vectors.json#2", "ask");
    assert!(!trapped.success);
    extract(
        &fixture,
        &replayed,
        &trapped.calldata,
        SimProfile::UnboundedV1,
    );
    assert_eq!((replayed.guest_runs(), replayed.memo_hits()), (1, 1));
}

#[test]
fn both_legs_sit_under_one_env_commitment() {
    // What the ffi leg metered with is on record: every golden vector carries
    // `cycles` and the `gasUsed` gk-run derived from them. Exactly one rate
    // explains them all, and it is the pinned one.
    let goldens: Vec<GoldenVectors> = GOLDEN_VECTORS
        .iter()
        .map(|json| serde_json::from_str(json).expect("golden vectors"))
        .collect();
    let explains = |rate: u64| {
        goldens
            .iter()
            .flat_map(|golden| &golden.vectors)
            .all(|vector| vector.gas_used == vector.cycles.div_ceil(rate))
    };
    let ffi_rates: Vec<u64> = (1..=64).filter(|rate| explains(*rate)).collect();
    assert_eq!(ffi_rates, [UNBOUNDED_V3_CYCLES_PER_GAS]);
    for vector in goldens.iter().flat_map(|golden| &golden.vectors) {
        assert_eq!(vector.gas_used, cycles_to_gas(vector.cycles));
    }
    // ... over the very ELF bytes the precompile leg installs.
    assert_eq!(goldens[0].program_hash, keccak256(HELLO_C));
    assert_eq!(goldens[1].program_hash, keccak256(BENCH_C));
    assert_eq!(goldens[2].program_hash, keccak256(BENCH_C));

    let ffi_env = GkvmEnv {
        spec_version: UNBOUNDED_V3_GKVM_SPEC_VERSION,
        cycles_per_gas: ffi_rates[0],
    };
    for profile in [SimProfile::UnboundedV1, SimProfile::UnboundedV1Xl] {
        let block = profile.block_gas_limit_override().expect("pinned");
        let tx = profile.tx_gas_limit_override().expect("pinned");
        assert_eq!(
            env_commitment_v3(block, tx, None, &ffi_env),
            env_commitment_v3(block, tx, None, &GkvmEnv::PINNED),
            "{profile:?}"
        );
    }
    // The S1 golden (core `v3_golden_vectors`): V1 tier, no overlay.
    let v1 = SimProfile::UnboundedV1;
    assert_eq!(
        env_commitment_v3(
            v1.block_gas_limit_override().expect("pinned"),
            v1.tx_gas_limit_override().expect("pinned"),
            None,
            &ffi_env
        ),
        alloy::primitives::b256!(
            "0x6cb5d625cfd62fbcc6bc1060ffafa657b6deb6f578a9a129a2d4188c0a8c6e6c"
        )
    );
}

/// The negative that documents the `requiresGuestVm` gate (doc risk 3): an
/// `rpc`-executor operator does not abstain on a V3 consumer. Its node has no
/// precompile, `GkVm.exec` reads the empty account as `GkVmUnavailable`, and
/// the executor deterministically extracts the revert transition — a signable
/// result that competes with the honest quorum's. Same task, same block: the
/// local executor with the program answers, without it abstains.
#[tokio::test(flavor = "multi_thread")]
async fn the_rpc_executor_turns_a_v3_task_into_the_gkvm_unavailable_revert_transition() {
    let fixture = fixture();
    let task = task(&fixture, "hello-c_vectors.json#1", "ask");
    let anvil = LocalAnvil::spawn().await; // vanilla: gkvm is absent on the applying chain
    let provider = anvil.provider();
    set_code(&provider, CONSUMER, fixture.consumer_code.clone()).await;

    // Directly executing the tracked function reverts GkVmUnavailable, exactly.
    let err = provider
        .call(task_request(&task.calldata))
        .await
        .expect_err("a V3 tracked function cannot execute on a real chain");
    let revert_data = err
        .as_error_resp()
        .and_then(|payload| payload.as_revert_data())
        .expect("revert data");
    assert_eq!(
        revert_data.as_ref(),
        errors::GkVmUnavailable {}.abi_encode()
    );

    // The rpc executor: the revert transition, the same bytes every time.
    let empty = encode_state_updates_to_abi(&[]);
    for _ in 0..2 {
        let (updates, _) = extract_state_updates_hybrid(
            &provider,
            task_request(&task.calldata),
            BlockId::latest(),
            CONSUMER,
            SimProfile::Chain,
            None,
        )
        .await
        .expect("the rpc executor does not abstain");
        assert_eq!(encode_state_updates_to_abi(&updates), empty);
    }

    // The local executor over the same anvil state, program installed: the
    // ffi leg's payload — not what the rpc executor would have signed.
    let local = |gkvm: Option<Arc<GkvmHost>>| {
        let any = any_provider(&anvil);
        let calldata = task.calldata.clone();
        async move {
            let env = anvil_local_block_env(&any).await;
            let backend = anvil_shared_backend(any, env.number);
            let mounts = ExecMounts {
                overlay: Default::default(),
                gkvm,
            };
            extract_state_updates_local(
                backend,
                mounts,
                env,
                local_tx(&calldata),
                SimProfile::Chain,
                CONSUMER,
            )
            .await
        }
    };
    let (updates, _) = local(Some(host())).await.expect("local extraction");
    assert_eq!(encode_state_updates_to_abi(&updates), task.storage_updates);
    assert_ne!(task.storage_updates, empty);

    // ... and without the program it abstains rather than agree with `rpc`.
    let err = local(None)
        .await
        .expect_err("an unconfigured local executor abstains");
    assert!(
        format!("{err:#}").contains("no guest programs are configured"),
        "{err:#}"
    );
}

/// Prints the `probe` guestGas under which the precompile's budget for an
/// 8-byte payload is exactly the pinned vectors' 1000 cycles — the value of
/// `PINNED_GUEST_GAS` in the sdk's `test/GkVmParity.t.sol`. A function of the
/// consumer bytecode: re-run after the fixture's `consumerCode` moves.
/// `cargo test -p gas-analyzer-evmsketch --lib tune_pinned_guest_gas -- --ignored --nocapture`
#[test]
#[ignore = "tuning aid, not an assertion"]
fn tune_pinned_guest_gas() {
    let fixture = fixture();
    let pinned = task(&fixture, "bench-c-limit1000_vectors.json#0", "probe");

    // probe(bytes32, bytes32, bytes, uint256 guestGas): the fourth head word.
    let limit_under = |guest_gas: u64| -> Option<u64> {
        let mut calldata = pinned.calldata.to_vec();
        calldata[4 + 96..4 + 128].copy_from_slice(&U256::from(guest_gas).to_be_bytes::<32>());
        let updates = extract(&fixture, &host(), &calldata.into(), SimProfile::Chain);
        let StateUpdate::Log3(log) = updates.last()? else {
            return None;
        };
        // abi.encode(bytes err): offset, length, then selector || used || limit.
        let err = log.data.get(64..64 + 68)?;
        (err[..4] == errors::GkGuestOutOfCycles::SELECTOR)
            .then(|| U256::from_be_slice(&err[36..68]).to::<u64>())
    };

    let (mut low, mut high) = (60_000u64, 200_000u64);
    while low < high {
        let mid = (low + high) / 2;
        match limit_under(mid) {
            Some(limit) if limit >= 1_000 => high = mid,
            _ => low = mid + 1,
        }
    }
    println!(
        "PINNED_GUEST_GAS = {low} (limit {:?}; one below: {:?})",
        limit_under(low),
        limit_under(low - 1)
    );
}
