//! UNBOUNDED_V3 M5 — the local-executor leg of the zero-glue check
//! (`answer.py → gk build → forge test → local executor`).
//!
//! The forge leg lives in gas-killer/solidity-sdk:
//! `test/examples/OnchainChatNativeZeroGlue.t.sol` runs every task as one
//! `ask` against `GasKillerChatNative` wired to `GkVmFfiShim` — the real
//! answer.py image (MicroPython over gk-guest-crt) under `gk-run` — and
//! records what the task did to the consumer as the encoded `StateUpdate`
//! payload (`tests/fixtures/gkvm/native_tasks.json`, regenerated by
//! `make -C tools/gk zero-glue`, together with the consumer's production
//! runtime bytecode, `gkvm = GKVM_ADDRESS`).
//!
//! Here: the same bytecode, the same calldata, through the local executor's
//! real extraction against the real precompile with the same image installed.
//! For every answered task the payload bytes must be identical; for the task
//! whose guest raises, the revert data must be (its payload is this
//! executor's revert-unaware one, which forge cannot observe — pinned below,
//! see `reverted_ask_payload`). Nothing between answer.py's type
//! hints and those bytes is hand-written — the consumer calls the binding
//! `gk build` generated, the guest's ABI codec is frozen into the image — so
//! this suite knows the consumer only as bytecode and the guest only as an
//! ELF: it decodes neither.
//!
//! The ~1 MB image is NOT committed (the sdk commits the binding, whose
//! `PROGRAM_HASH` commits to the image, and rebuilds the ELF reproducibly).
//! The tests that need it are `#[ignore]`d and FAIL when it is absent rather
//! than pass vacuously: `GK_NATIVE_ANSWER_ELF`, else the sibling sdk
//! checkout's `cache/gkvm/build/native-answer/guest.elf`.
//! `make -C ../solidity-sdk/tools/gk zero-glue-check` runs the whole chain.

use super::*;
use crate::local_exec::{
    ExecMounts, call_view_local_blocking, extract_state_updates_local_blocking,
};
use alloy::primitives::keccak256;
use gas_analyzer_core::gkvm::GKVM_ADDRESS;
use gas_analyzer_core::gkvm::errors::{self, SolError};
use gas_analyzer_core::sim_profile::STATE_TRACKER_SLOT;
use gas_analyzer_core::validate_unbounded_shape;
use gas_analyzer_gkvm::{GuestProgramSet, LoadedGuestProgram};
use revm::database::{CacheDB, EmptyDB};
use revm::state::{AccountInfo, Bytecode};

const NATIVE_TASKS: &str = include_str!("../../tests/fixtures/gkvm/native_tasks.json");

/// Where the sdk's `gk build` leaves the answer.py image, seen from this crate.
const SIBLING_SDK_ELF: &str = concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/../../../solidity-sdk/cache/gkvm/build/native-answer/guest.elf"
);

const CALLER: Address = address!("0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266");
const CONSUMER: Address = address!("0x00000000000000000000000000000000000050a2");

#[derive(serde::Deserialize)]
#[serde(rename_all = "camelCase")]
struct NativeFixture {
    gkvm_address: Address,
    program_hash: B256,
    consumer_code: Bytes,
    tasks: Vec<NativeTask>,
}

/// One forge-leg task: `calldata` sent to a fresh consumer, and the encoded
/// payload forge observed. A task whose tracked call reverted carries its
/// `revert_data` and NO payload: forge sees only what survived the revert,
/// while this executor's extraction of a reverted call is revert-unaware (see
/// `local_exec`'s `reverted_call_extracts_rolled_back_ops`) — that payload is
/// pinned here, not recorded there.
#[derive(serde::Deserialize)]
#[serde(rename_all = "camelCase")]
struct NativeTask {
    name: String,
    calldata: Bytes,
    success: bool,
    revert_data: Bytes,
    #[serde(default)]
    storage_updates: Option<Bytes>,
}

/// What the local executor extracts from an `ask` whose guest trapped: the
/// `trackState` bump that preceded the guest call, rolled back on a real chain
/// but kept by the revert-unaware replay pass — the same payload any reverting
/// `trackState` function yields on this stack, guest or no guest.
fn reverted_ask_payload() -> Bytes {
    encode_state_updates_to_abi(&[StateUpdate::Store(IStateUpdateTypes::Store {
        slot: STATE_TRACKER_SLOT,
        value: B256::with_last_byte(1),
    })])
}

fn fixture() -> NativeFixture {
    let fixture: NativeFixture = serde_json::from_str(NATIVE_TASKS).expect("native_tasks.json");
    assert_eq!(
        fixture.gkvm_address, GKVM_ADDRESS,
        "forge leg built for another precompile address"
    );
    fixture
}

/// The answer.py image, which must be the very program the fixture's consumer
/// names: a rebuilt guest that moved is a different task, not a parity failure.
fn answer_elf(fixture: &NativeFixture) -> Vec<u8> {
    let path = std::env::var("GK_NATIVE_ANSWER_ELF").unwrap_or_else(|_| SIBLING_SDK_ELF.into());
    let elf = std::fs::read(&path).unwrap_or_else(|e| {
        panic!(
            "answer.py image not found at {path} ({e}): build it with \
             `make -C ../solidity-sdk/tools/gk native-example` or set GK_NATIVE_ANSWER_ELF"
        )
    });
    assert_eq!(
        keccak256(&elf),
        fixture.program_hash,
        "{path} is not the image the committed binding names"
    );
    elf
}

fn host(elf: &[u8]) -> Arc<GkvmHost> {
    let mut programs = GuestProgramSet::default();
    programs.insert_program(
        LoadedGuestProgram::from_bytes(elf.to_vec(), keccak256(elf), "<answer.py image>")
            .expect("image loads"),
    );
    Arc::new(GkvmHost::new(programs))
}

fn mounts(host: Option<&Arc<GkvmHost>>) -> ExecMounts {
    ExecMounts {
        overlay: Default::default(),
        gkvm: host.cloned(),
    }
}

/// A fresh consumer, as on the forge leg: production bytecode, all-zero
/// storage (`ask` reads nothing the constructor wrote).
fn consumer_db(fixture: &NativeFixture) -> CacheDB<EmptyDB> {
    let mut db = CacheDB::new(EmptyDB::default());
    db.insert_account_info(
        CONSUMER,
        AccountInfo::from_bytecode(Bytecode::new_raw(fixture.consumer_code.clone())),
    );
    db
}

fn block_env() -> LocalBlockEnv {
    LocalBlockEnv {
        chain_id: 31_337,
        spec: SpecId::PRAGUE,
        number: 100,
        timestamp: 1_700_000_000,
        gas_limit: 30_000_000,
        coinbase: Address::ZERO,
        prevrandao: B256::ZERO,
        basefee: 0,
        difficulty: U256::ZERO,
    }
}

fn local_tx(calldata: &Bytes) -> LocalTxRequest {
    let request = TransactionRequest::default()
        .from(CALLER)
        .to(CONSUMER)
        .gas_limit(30_000_000)
        .input(calldata.clone().into());
    LocalTxRequest::from_request(&request).expect("valid tx request")
}

fn extract(
    fixture: &NativeFixture,
    host: Option<&Arc<GkvmHost>>,
    calldata: &Bytes,
    profile: SimProfile,
) -> anyhow::Result<Vec<StateUpdate>> {
    extract_state_updates_local_blocking(
        consumer_db(fixture),
        mounts(host),
        &block_env(),
        &local_tx(calldata),
        profile,
        CONSUMER,
    )
    .map(|(updates, _)| updates)
}

#[test]
#[ignore = "needs the answer.py image (not committed): make -C ../solidity-sdk/tools/gk zero-glue-check"]
fn forge_and_local_executor_tasks_encode_identical_state_updates() {
    let fixture = fixture();
    let elf = answer_elf(&fixture);
    assert_eq!(fixture.tasks.len(), 6);
    assert!(fixture.tasks.iter().any(|task| !task.success));

    // Chain is the forge-like env; UnboundedV1 is the profile V3 consumers
    // run under (2^40 gas, single-slot payload shape enforced).
    for profile in [SimProfile::Chain, SimProfile::UnboundedV1] {
        for task in &fixture.tasks {
            let host = host(&elf);
            let updates =
                extract(&fixture, Some(&host), &task.calldata, profile).expect("local extraction");
            if task.success {
                assert_eq!(
                    Some(encode_state_updates_to_abi(&updates)),
                    task.storage_updates,
                    "{} under {profile:?}: local-executor payload diverged from the forge leg\n  \
                     local: {updates:?}",
                    task.name
                );

                // GasKillerChat's shape, natively: the chat root, the
                // gate-exempt transition counter, the answer log.
                let shape = validate_unbounded_shape(&updates).expect("unbounded payload shape");
                assert_eq!(
                    (shape.stores, shape.tracker_stores, shape.calls, shape.logs),
                    (1, 1, 0, 1),
                    "{}",
                    task.name
                );
                // One pass reached the guest: classification needed no fallback.
                assert_eq!(
                    (host.guest_runs(), host.memo_hits()),
                    (1, 0),
                    "{}",
                    task.name
                );
            } else {
                // The bubbled Python exception reverts the tracked call. No
                // answer is extracted — only the rolled-back tracker bump the
                // revert-unaware replay pass keeps — and the classify → replay
                // fallback is answered from the memo, not by a second run.
                assert_eq!(
                    encode_state_updates_to_abi(&updates),
                    reverted_ask_payload(),
                    "{} under {profile:?}: {updates:?}",
                    task.name
                );
                assert_eq!(
                    (host.guest_runs(), host.memo_hits()),
                    (1, 1),
                    "{}",
                    task.name
                );
                // The revert reason — a typed trap carrying the traceback —
                // is the forge leg's, byte for byte.
                assert_eq!(task.revert_data[..4], errors::GkGuestTrap::SELECTOR);
                let err = call_view_local_blocking(
                    consumer_db(&fixture),
                    mounts(Some(&host)),
                    &block_env(),
                    &local_tx(&task.calldata),
                    profile,
                )
                .expect_err("the tracked call reverts");
                assert!(
                    format!("{err:#}").contains(&task.revert_data.to_string()),
                    "{}: revert data diverged: {err:#}",
                    task.name
                );
            }
        }
    }
}

/// Needs no image, so it always runs: the fixture is what this suite thinks
/// it is, and an operator that has not installed the consumer's program
/// abstains on every task instead of signing anything.
#[test]
fn a_native_task_without_the_program_abstains() {
    let fixture = fixture();
    assert_eq!(fixture.tasks.len(), 6);
    for task in &fixture.tasks {
        // ask(uint256[],uint256), whatever the task
        assert_eq!(task.calldata[..4], keccak256("ask(uint256[],uint256)")[..4]);
        assert_eq!(task.success, task.revert_data.is_empty(), "{}", task.name);
        assert_eq!(
            task.success,
            task.storage_updates.is_some(),
            "{}",
            task.name
        );
    }
    // The tracker slot is the one the unbounded shape exempts (the forge leg
    // records it as a plain STORE).
    let tracker = STATE_TRACKER_SLOT.to_string();
    let answered = &fixture.tasks[0];
    assert!(answered.success);
    let recorded = answered.storage_updates.as_ref().expect("payload");
    assert!(
        recorded
            .to_string()
            .contains(tracker.trim_start_matches("0x"))
    );

    // Another program installed, not this consumer's: environment failure.
    let other: &[u8] = include_bytes!("../../../gkvm/tests/fixtures/hello-c.elf");
    let other = host(other);
    let err = extract(
        &fixture,
        Some(&other),
        &answered.calldata,
        SimProfile::UnboundedV1,
    )
    .expect_err("an operator without the program abstains");
    assert!(format!("{err:#}").contains("not installed"), "{err:#}");
    assert!(
        format!("{err:#}").contains(&fixture.program_hash.to_string()),
        "{err:#}"
    );
    assert_eq!(other.guest_runs(), 0);

    // No guest programs at all: the same class.
    let err = extract(&fixture, None, &answered.calldata, SimProfile::UnboundedV1)
        .expect_err("an unconfigured local executor abstains");
    assert!(
        format!("{err:#}").contains("no guest programs are configured"),
        "{err:#}"
    );
}
