//! V3 leg of the setCode-drop measurement (`scripts/setcode-bench`).
//!
//! The V2 e2e mounts the model on the chain anvil with one `anvil_setCode` per
//! 24,575-byte overlay chunk — 24,299 of them for Qwen3-0.6B. Under V3 the
//! weights never touch the chain node: they arrive as a `GK_GUEST_ARTIFACT`
//! mount, whose whole cost is [`ArtifactMountV3::from_files`] (mmap + one
//! Merkle pass + the root check). This bench times exactly that call over the
//! same files the V2 leg feeds to `deploy_anvil.py --overlay`.
//!
//! `#[ignore]`d: it is a measurement, not an assertion, and it reads ~600MB.
//! Run it through `make -C crates/gkvm/scripts/setcode-bench v3`.
//!
//! Artifacts come from `GK_BENCH_ARTIFACTS` (a directory holding `weights.bin`
//! and `tokenizer.bin`, e.g. the real qwen3-0.6b-onchain-v1 release assets). When
//! the directory has no `weights.bin`, a SYNTHETIC stand-in is generated there:
//! deterministic pseudo-random bytes sized to split into exactly the 24,299
//! chunks of the real model. Both legs are content-independent up to noise
//! (hex/JSON/keccak/mmap are all linear in length), but the output says
//! `"synthetic":true` so a number is never mistaken for a real-weights run.

use gas_analyzer_gkvm::{ArtifactMountV3, manifest};
use std::{
    io::Write,
    path::{Path, PathBuf},
    time::Instant,
};

/// `deploy_anvil.py`'s chunk size (one data contract minus the STOP prefix).
const OVERLAY_CHUNK: u64 = 24_575;
/// Qwen3-0.6B's overlay chunk count (UNBOUNDED_V3_NATIVE.md).
const QWEN3_OVERLAY_CHUNKS: u64 = 24_299;
/// Synthetic tokenizer size: the real one is ~1.6MB (TESTNET.md) → 66 chunks.
const SYNTHETIC_TOKENIZER_LEN: u64 = 1_600_000;
/// Marker file recording that this directory's blobs are the stand-in.
const SYNTHETIC_MARKER: &str = "SYNTHETIC";

fn artifacts_dir() -> PathBuf {
    match std::env::var_os("GK_BENCH_ARTIFACTS") {
        Some(dir) => PathBuf::from(dir),
        None => {
            Path::new(env!("CARGO_MANIFEST_DIR")).join("../../target/gkvm-setcode-bench/artifacts")
        }
    }
}

fn overlay_chunks(len: u64) -> u64 {
    len.div_ceil(OVERLAY_CHUNK)
}

/// xorshift64* — a fixed stream, so the stand-in (and its root) is reproducible.
fn write_pseudo_random(path: &Path, len: u64, mut state: u64) {
    let mut out = std::io::BufWriter::new(std::fs::File::create(path).expect("create blob"));
    let mut left = len;
    while left > 0 {
        state ^= state >> 12;
        state ^= state << 25;
        state ^= state >> 27;
        let word = state.wrapping_mul(0x2545_F491_4F6C_DD1D).to_le_bytes();
        let take = left.min(8) as usize;
        out.write_all(&word[..take]).expect("write blob");
        left -= take as u64;
    }
    out.flush().expect("flush blob");
}

/// Generates the stand-in unless the directory already holds a `weights.bin`
/// (real or synthetic) — existing artifacts are never overwritten.
fn ensure_artifacts(dir: &Path) {
    if dir.join("weights.bin").exists() {
        return;
    }
    std::fs::create_dir_all(dir).expect("create artifacts dir");
    let tokenizer_chunks = overlay_chunks(SYNTHETIC_TOKENIZER_LEN);
    let weights_len = (QWEN3_OVERLAY_CHUNKS - tokenizer_chunks) * OVERLAY_CHUNK;
    write_pseudo_random(&dir.join("weights.bin"), weights_len, 0x9E37_79B9_7F4A_7C15);
    write_pseudo_random(
        &dir.join("tokenizer.bin"),
        SYNTHETIC_TOKENIZER_LEN,
        0xD1B5_4A32_D192_ED03,
    );
    // deploy_anvil.py echoes these two keys; the overlay path needs nothing else.
    std::fs::write(
        dir.join("vectors.json"),
        "{\"packedConfig\": [], \"promptIds\": []}\n",
    )
    .expect("write vectors.json");
    std::fs::write(
        dir.join(SYNTHETIC_MARKER),
        "size-identical stand-in generated by artifact_mount_bench.rs — NOT model weights\n",
    )
    .expect("write marker");
}

#[test]
#[ignore = "measurement, not an assertion: make -C crates/gkvm/scripts/setcode-bench v3"]
fn artifact_mount_wall_clock() {
    let dir = artifacts_dir();
    ensure_artifacts(&dir);
    let weights = dir.join("weights.bin");
    let tokenizer = dir.join("tokenizer.bin");
    let paths = [weights.as_path(), tokenizer.as_path()];
    let lens = paths.map(|p| std::fs::metadata(p).expect("artifact file").len());
    let samples: usize = std::env::var("GK_BENCH_SAMPLES")
        .ok()
        .and_then(|s| s.parse().ok())
        .unwrap_or(3);

    // Producer side, once and untimed against the mount: the root an operator
    // is configured with (`GK_GUEST_ARTIFACT_ROOT`).
    let started = Instant::now();
    let manifests: Vec<_> = paths
        .iter()
        .map(|p| manifest::ArtifactFileManifest::from_bytes(&std::fs::read(p).expect("read")))
        .collect();
    let root = manifest::artifact_root(&manifests);
    let producer_nanos = started.elapsed().as_nanos();

    println!(
        "{{\"leg\":\"v3-mount\",\"synthetic\":{},\"weights_bytes\":{},\"tokenizer_bytes\":{},\
         \"overlay_chunks\":{},\"pages\":{},\"artifact_root\":\"{root}\",\"producer_nanos\":{producer_nanos},\
         \"profile\":\"{}\"}}",
        dir.join(SYNTHETIC_MARKER).exists(),
        lens[0],
        lens[1],
        overlay_chunks(lens[0]) + overlay_chunks(lens[1]),
        manifests.iter().map(|m| m.page_count()).sum::<u64>(),
        if cfg!(debug_assertions) {
            "debug"
        } else {
            "release"
        },
    );

    for sample in 0..samples {
        let started = Instant::now();
        let mount = ArtifactMountV3::from_files(&paths, root).expect("mount verifies");
        let wall_nanos = started.elapsed().as_nanos();
        assert_eq!(mount.root, root);
        println!("{{\"leg\":\"v3-mount\",\"sample\":{sample},\"wall_nanos\":{wall_nanos}}}");
    }
}
